### ISSUE TITLE
Partition and Annotation txt files

### ISSUE THREAD

**Issue by J-Fo-S** [wdyin/GeoGAN#1]
Hello, would you be able to make the partition and annotation txt files required for the code available? As you probably know, the download links for the official dataset site are disabled. I resorted to finding csv versions from this site: https://www.kaggle.com/jessicali9530/celeba-dataset

However, they are throwing index errors when I try to run the training with them. I cannot divine how the files the authors used where indexed, so it would be most helpful if the necessary files could be made available. Thank you

**Comment by wdyin** [comment]
There are some new sources avaliable.
Google Drive:
https://drive.google.com/open?id=0B7EVK8r0v71pWEZsZE9oNnFzTm8

Baidu:
http://pan.baidu.com/s/1eSNpdRG
